### ISSUE TITLE
"Select Lean Toolchain" does not restart server

### ISSUE THREAD

**Issue by Kha** [leanprover/vscode-lean4#111]
When selecting a different toolchain with a file with `#eval Lean.versionString` open, the output is updated only when explicitly restarting the server. I would expect it to be restarted immediately.

**Comment by lovettchris** [comment]
Fixed in #121 , can you verify?

**Comment by lovettchris** [comment]
Fixed more in https://github.com/leanprover/vscode-lean4/pull/127, can you verify?
