### ISSUE TITLE
No diagnostics when opening single files

### ISSUE THREAD

**Issue by gebner** [leanprover/vscode-lean4#113]
That is, starting vscode with `code a/b/c.lean` from the command-line.

https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/making.20lean.20and.20lean4.20coexist/near/270627131

**Comment by lovettchris** [comment]
Fixed in https://github.com/leanprover/vscode-lean4/pull/118

**Comment by lovettchris** [comment]
Fixed more bugs related to this scenario in https://github.com/leanprover/vscode-lean4/pull/127
