### ISSUE TITLE
Infoview not working for external file.

### ISSUE THREAD

**Issue by Seiryn21** [leanprover/vscode-lean4#115]
Infoview doesn't show the context in files located outside the working directory and sub directories.

### How to reproduce
```sh
$ lake new minimal
$ cd minimal
$ code .
```
open Main.lean
Infoview shows the context
open ~/.elan/toolchains/leanprover--lean4---nightly-2022-02-05/src/lean/Init/System/IO.lean
Lean infoview doesn't show the context

### Versions
lean version : leanprover/lean4:nightly-2022-02-05
vscode-lean4 version : 0.0.63
last  version without the bug : 0.0.59

### Additional informations
Runtime status shows an uncaught error when opening IO.lean : Cannot read property 'filter' of undefined

**Comment by Seiryn21** [comment]
I worked on a possible fix in which a special LeanClient is created for files without a workspace folder. 
While it seems to fix the issue it could create others, as i'm not familiar with the codebase.

Here is my potential fix: Seiryn21/vscode-lean4@fec6c27f

**Comment by gebner** [comment]
I think this is the same issue as #113.  @lovettchris Can you take care of this?

**Comment by Seiryn21** [comment]
Ah yes, it is the same issue indeed.

**Comment by lovettchris** [comment]
> I think this is the same issue as #113. @lovettchris Can you take care of this?

I'm investigating...

**Comment by lovettchris** [comment]
I have a fix:
![image](https://user-images.githubusercontent.com/18707114/152902173-0e0bef7e-b83f-43b5-be4b-f9a80ebd4b81.png)

**Comment by lovettchris** [comment]
See https://github.com/leanprover/vscode-lean4/pull/117
I have some questions there.
