### ISSUE TITLE
Properly detect lean4 directory

### ISSUE THREAD

**Issue by gebner** [leanprover/vscode-lean4#124]
Neither the `lean4` repository nor the nightly distribution (i.e., what's in `~/.elan/toolchains/.../`) contain `lean-toolchain` or `lakefile.lean` files.  Therefore the extension didn't detect it as a root, and failed to start an LSP server for these directories (causing #122).

In 2c6bdfc7aa7a20a17d11c752382b404a776554bc I've put in a quick fix that checks for `LICENSE`&`LICENSES` files. That's probably broken for older lean versions, and not really future-proof either.

**Comment by Kha** [comment]
I was mostly thinking about folder-opening projects without a lakefile.lean here btw. In the "jump to stdlib" use case, I assume `wsFolder` would be `null`, so I understand that the hack would still be necessary there.
