### ISSUE TITLE
Update .gitignore in order to not include local files

### ISSUE THREAD

**Issue by marianaalanis93** [leanprover/vscode-lean4#126]
Update .gitignore in order to not include local files that are automatically created, such as:

## Some extra outputs:
/build
/lean_packages

## Local files
package-lock.json
package.json
vscode-lean4/package-lock.json

**Comment by marianaalanis93** [comment]
#128 PR referenced to this issue: https://github.com/leanprover/vscode-lean4/pull/128

**Comment by lovettchris** [comment]
I'm confused, the package-lock.json, package.json, vscode-lean4/package-lock.json are all very much checked in and need to be checked in and updated as version dependencies change.

The `build` and `lean_packages` folders, how are you getting those?  When I run the following build process I do not get these folders on my machine:
```
npm install
npx lerna bootstrap
npx lerna run build
```
and `git status` shows nothing.  Instead I get an `out` and `dist` folders and those are already listed in the .gitignore.

**Comment by marianaalanis93** [comment]
Closing this issue based in our last conversations about this (@lovettchris and myself)
