### ISSUE TITLE
Autocompletion after inputting an underscore

### ISSUE THREAD

**Issue by javra** [leanprover/vscode-lean4#14]
I noticed that the autocompletion box opens whenever I want to input a placeholder `_`, which is pretty annoying. It offers me to complete to `_law`, of which I have no idea where it comes from.

**Comment by lovettchris** [comment]
You must have _law defined somewhere in your context.  Can you try typing "Ctrl+Space" in the same location you would have typed "_" and see if it is in that list ?

**Comment by leodemoura** [comment]
@javra Yes, this is really annoying.

**Comment by lovettchris** [comment]
See https://github.com/leanprover/lean4/pull/1639

**Comment by javra** [comment]
Thanks a bunch!! :partying_face: :pray:

**Comment by mhuisi** [comment]
I can't reproduce this issue anymore.
