### ISSUE TITLE
Spurious error from eslint extension

### ISSUE THREAD

**Issue by gebner** [leanprover/vscode-lean4#146]
I'm using the eslint extension for vscode, and I get the following error on most files:
```
Parsing error: Cannot read file '/home/gebner/vscode-lean4/vscode-lean4/lean4-infoview-api/tsconfig.json'. eslint
```
This is a bit annoying since vscode complains about the error every time I try to debug the extension.  Running `npm run lint` on the command line succeeds.

**Comment by Vtec234** [comment]
Closed in #149.
