### ISSUE TITLE
`insertText` is broken when no position is specified.

### ISSUE THREAD

**Issue by Vtec234** [leanprover/vscode-lean4#152]
Per the [API](https://github.com/leanprover/vscode-lean4/blob/e0870d3eba00985f17563bdc1ce990964cb0952e/lean4-infoview-api/src/infoviewApi.ts#L52), `insertText` should write at the current cursor location when `pos === undefined`. This seems to have been broken since #104. /CC @lovettchris

**Comment by lovettchris** [comment]
Thanks, see https://github.com/leanprover/vscode-lean4/pull/153
