### ISSUE TITLE
No notification if server is killed

### ISSUE THREAD

**Issue by gebner** [leanprover/vscode-lean4#155]
If the user terminates the Lean server process manually, no error message is shown and the infoview no longer updates (it will show the last goal even if you move around the file).

Very confusingly, other files remain functional and still get updated with diagnostics, etc.  This is because the LSP library restarts the server automatically and this somehow messes up the currently open file.

 - The infoview should indicate the server status, see #114 
 - An error message should be shown (like we did in Lean 3)
 - IMHO we should disable the retry logic of the LSP library because it doesn't make any sense for us.

**Comment by marianaalanis93** [comment]
Fixed in https://github.com/leanprover/vscode-lean4/issues/114
