### ISSUE TITLE
Tests failing on Windows

### ISSUE THREAD

**Issue by Vtec234** [leanprover/vscode-lean4#165]
We are seeing some non-deterministic failures of the tests on Windows. For example, [here](https://github.com/leanprover/vscode-lean4/runs/5982021889?check_suite_focus=true) we see
```
AssertionError [ERR_ASSERTION]: Missing "master" in infoview
```
CC @lovettchris

**Comment by clovett** [comment]
Interesting the infoview dump in that log shows this is the deaded info view no updating even though there should be 2 messages to show they are not showing:

![image](https://user-images.githubusercontent.com/3336415/163080562-cde28e92-6694-4999-8073-e4a56b3126fd.png)

**Comment by clovett** [comment]
All the subsequent `rejected promise not handled within 1 second: Error [ERR_STREAM_WRITE_AFTER_END]: write after end
` error should actually be fixed by the upgrade in https://github.com/leanprover/vscode-lean4/pull/162

**Comment by lovettchris** [comment]
I believe this is fixed now.
