### ISSUE TITLE
Broken infoview in Gitpod with 0.0.70+

### ISSUE THREAD

**Issue by Kha** [leanprover/vscode-lean4#166]
Starting with version 0.0.69, the infoview is empty on gitpod.io, presumably due to this error in the console:
```
Uncaught TypeError: Error resolving module specifier “@lean4/infoview”. Relative module specifiers must start with “./”, “../” or “/”.
```
Example: https://gitpod.io/#https://github.com/Kha/tba-2022

**Comment by gebner** [comment]
I guess this is due to #151.

cc @Vtec234

**Comment by Vtec234** [comment]
Ahhhh, it's because only Chromium [supports `importmap`s](https://caniuse.com/import-maps). By the way, this only appears in 0.0.70+ - 0.0.69 should still work.
