### ISSUE TITLE
Infoview shows incorrect expected type

### ISSUE THREAD

**Issue by int-y1** [leanprover/vscode-lean4#168]
In this screenshot, the expected type is shown as `⊢ ∃ x, q x ∧ x x`, when it should be `⊢ ∃ x, q x ∧ p x`.

![Capture](https://user-images.githubusercontent.com/14223529/163701392-185631ba-54a0-427c-a339-9bf16520b40f.PNG)

```lean
-- try it 
variable (α : Type) (p q : α → Prop)

example (h : ∃ x, p x ∧ q x) : ∃ x, q x ∧ p x :=
  Exists.elim h
    (fun w =>
     fun hw : p w ∧ q w =>
     show ∃ x, q x ∧ p x from ⟨w, hw.right, hw.left⟩)
```

---

Additional details:
- My OS is Windows 10 version 21H2.
- The version of my Lean 4 extension is v0.0.70.
- I'm running Lean `v4.0.0-m4`. `lean --version` returns `Lean (version 4.0.0, commit 96de208a6b1a, Release)`.
- Restarting my computer didn't fix this issue.

**Comment by leodemoura** [comment]
This has been fixed.

![image](https://user-images.githubusercontent.com/2778936/176252690-a6b821d5-81ef-4061-a01a-011b368db942.png)
