### ISSUE TITLE
Mark some `end`-tokens as unbalanced

### ISSUE THREAD

**Issue by gebner** [leanprover/vscode-lean4#174]
Since the latest vscode update (1.67), the `end` token is highlighted in red for me:
```
section a
end a
```

This seems to be related to the bracket pair colorization feature, which is now enabled by default:
https://code.visualstudio.com/updates/v1_67#_textmate-grammars-can-mark-tokens-as-unbalanced

**Comment by leodemoura** [comment]
@gebner Is this still a problem for you? I cannot reproduce it.
