### ISSUE TITLE
"Failed to start language server" popup is too generic

### ISSUE THREAD

**Issue by Kha** [leanprover/vscode-lean4#181]
The server could fail to start due to various reasons, but the popup does not show the actual error (or instruct users how to find it), nor does it hide the "install Elan" button when that is unlikely to be helpful.

![image](https://user-images.githubusercontent.com/109126/169322661-e1137b7b-38bf-41ac-9920-96318e2a713f.png)

**Comment by Kha** [comment]
I don't think it's displayed by default, is it?

**Comment by lovettchris** [comment]
Good point, I used to pop up the output window automatically in this case, but the someone said they didn't like that :-(

**Comment by lovettchris** [comment]
But I could add a button "see output" that does that...
