### ISSUE TITLE
Include namespacing in breadcrumbs

### ISSUE THREAD

**Issue by ydewit** [leanprover/vscode-lean4#188]
It seems that there is no breadcrumb information in the extension beyond the file based one provided by default by VS Code:

![image](https://user-images.githubusercontent.com/1335/171658519-d23ded1a-4f24-4f3e-984e-05097fb039c6.png)

Especially considering that namespaces do not have to match the file & folder structure and they can be created and nested at will within the same .lean file, it seems important to be able to know exactly the full namespace of a definition.

Here is an example of a breadcrumb with namespace information from the [breadcrumbs](https://code.visualstudio.com/docs/editor/editingevolved#_breadcrumbs) VS Code documentation.

![image](https://user-images.githubusercontent.com/1335/171659347-c9e88616-a476-4d0f-a463-06165fd1c037.png)

Note also that the breadcrumb above uses a path that is relative to the project folder avoiding unnecessary extra noise.

**Comment by ydewit** [comment]
Humm ... I had both of these installed:

![image](https://user-images.githubusercontent.com/1335/171667841-20b58fa3-5b45-4a1b-a81d-acf62468763e.png)

I assumed I had to have both, but maybe that is a wrong assumption?

**Comment by ydewit** [comment]
With only the Lean4 extension, I see the breadcrumbs!

Sorry for the noise.

**Comment by gebner** [comment]
The extension has some heuristics to detect whether a project is Lean 3 or Lean 4.  Maybe it detected your project incorrectly as Lean 3.

I've also updated the description of the `lean` extension to clarify that it is indeed for Lean 3.
