### ISSUE TITLE
Infoview docstrings should render in markdown.

### ISSUE THREAD

**Issue by EdAyers** [leanprover/vscode-lean4#196]
Currently if you click on a term in the infoview which has a docstring, it will render the docstring in the popup but it will be in code. However the docstrings in Lean are usually in markdown, so it would be cool to have a markdown render in the tooltip appear, also with some scrolling so that it doesn't consume the infoview if the docstring is big.

![image](https://user-images.githubusercontent.com/5064353/174389538-f3ffc046-bbed-452d-bf9b-75ae5d41778b.png)

The line to insert this is here.
https://github.com/leanprover/vscode-lean4/blob/c1d4665767882424c3831a18606a9beac1db6e57/lean4-infoview/src/infoview/interactiveCode.tsx#L58

**Comment by lovettchris** [comment]
@gebner  What do you have in your editor to produce that infoview content?  I'd like to test it.
