### ISSUE TITLE
Figure out if we want to do anything fun with hyperlinks in tooltips

### ISSUE THREAD

**Issue by lovettchris** [leanprover/vscode-lean4#212]
Hyperlinks containing absolute URL's already work and popup in your web browser, for example this:
![image](https://user-images.githubusercontent.com/18707114/177619394-6da9ac19-a96c-4285-ab31-b864c8309c30.png)

pops up like this:
![image](https://user-images.githubusercontent.com/18707114/177619466-5e4beb9e-f79a-4597-8f3a-fb1d4756ac78.png)

and you can click the link to open the URL in your web browser, this works both in the vscode editor and in the InfoView.

But is there anything fun we want to do with internal references to other types, more like a goto definition where one tip can jump to another tip and another as you follow the chain of related types?

If so, we need to design this work item UX experience, look and see if any other languages already do this (for consistency) and then implement it.

**Comment by mhuisi** [comment]
Closing because this is more of a server issue (c.f. https://github.com/leanprover/lean4/issues/1117).
