### ISSUE TITLE
Untitled files no longer work

### ISSUE THREAD

**Issue by gebner** [leanprover/vscode-lean4#227]
Using untitled files does not (longer?) seem to work with the current release of the extension.  I am a bit confused, because we have tests for this and they pass.  I have `elan` installed, the default Lean version is set to today's nightly, and I've opened a Lean 4 project.  Concretely:

1. Open `mathlib4`.
2. Ctrl-Shift-P "Create: New File..."
3. "Text File"
4. "Select a language"
5. "lean4"
6. No diagnostics are shown, and the infoview says "Waiting for Lean server to start..."

**Comment by lovettchris** [comment]
I cannot reproduce this in lean extension version v0.0.87 with the following your steps, and lean version `"4.0.0-nightly-2022-07-24".

Note: you will get the message "Waiting for lean server to start..." for ever if you have no elan installed and no lean in your path and the extension is waiting on you to press one of these buttons:

![image](https://user-images.githubusercontent.com/18707114/180901883-37671b57-2844-46a4-a767-8ccbaeb20952.png)

**Comment by lovettchris** [comment]
I wonder if it was busy installing "4.0.0-nightly-2022-07-04" and you just needed to wait a bit longer?

**Comment by lovettchris** [comment]
I have a potential fix here: https://github.com/leanprover/vscode-lean4/pull/231
