### ISSUE TITLE
`checkLakeVersion` breaks when used with a Lake not in `PATH`

### ISSUE THREAD

**Issue by tydeu** [leanprover/vscode-lean4#232]
When determining whether to use Lake when no toolchain file is present, `checkLakeVersion` is called:

https://github.com/leanprover/vscode-lean4/blob/a154c97ef6541ec7d1b6b5f7480d684c627d54c0/vscode-lean4/src/leanclient.ts#L168

`checkLakeVersion` invokes Lake via `batchExecute`:

https://github.com/leanprover/vscode-lean4/blob/a154c97ef6541ec7d1b6b5f7480d684c627d54c0/vscode-lean4/src/leanclient.ts#L546

which requires that the executable specified be in `PATH`:

https://github.com/leanprover/vscode-lean4/blob/a154c97ef6541ec7d1b6b5f7480d684c627d54c0/vscode-lean4/src/utils/batch.ts#L25-L29

Thus, the invocation fails when the Lake has been manually specified -- either through a general toolchain path or a direct Lake path.

Based on the comment in `batchExecute`, the `PATH` check only appears to be for testing purposes, so one way to fix this issue would be to condition the check based on whether `batchExecute` is being used for testing. Alternatively, a different method could be used for invoking Lake.

**Comment by tydeu** [comment]
I am willing to PR a fix if desired. I raised this issue first because I would like to agree on how this issue should be solved before doing so.

**Comment by lovettchris** [comment]
I implemented the suggested fix using the isRunningTest helper method.

**Comment by tydeu** [comment]
@lovettchris LGTM
