### ISSUE TITLE
Lean Language Server has stopped unexpectedly

### ISSUE THREAD

**Issue by lovettchris** [leanprover/vscode-lean4#235]
I'm getting these error messages while browsing around the Lake code base, and the messages  happen when I close a lean source file, which seems bogus to me.  I'm not sure if this an expected LSP error that needs to be suppressed by the vscode extension, or it is a new regression in the LSP?

![image](https://user-images.githubusercontent.com/18707114/182471758-ee7f250b-1339-485d-a4dc-45d9e52747c7.png)

**Comment by marianaalanis93** [comment]
Seems a bug to me but I'll check if this is expected 👌 .

**Comment by marianaalanis93** [comment]
Finally find a way to reproduce this issue, it seems that in some way when we are trying to update certain file (in the example below toolchain file), and want to refresh the window (or refresh dependencies) the server is not caching the correct state of the file that results in an error.

![image](https://user-images.githubusercontent.com/40707114/182964033-d7cc44d1-383c-4120-b4c8-955803a06736.png)

It's definitely a bug in my opinion. I'll find a way to address it
