### ISSUE TITLE
Problems not cleared when file is closed

### ISSUE THREAD

**Issue by lovettchris** [leanprover/vscode-lean4#250]
Notice all the problems listed for "ListComprehensions.lean" are still visible even though the file has been closed:

![image](https://user-images.githubusercontent.com/18707114/189749263-2a38b24b-6334-4a29-ac0d-1e0be222a149.png)

Also, it would be ideal the blue squiggles wouldn't be listed as problems in the first place.  See [Zulip Thread](https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/blue.20squiggly.20lines).

**Comment by lovettchris** [comment]
Should be fixed by https://github.com/leanprover/lean4/pull/1591

**Comment by Vtec234** [comment]
@lovettchris is it fixed? Can this be closed?

**Comment by lovettchris** [comment]
Yes https://github.com/leanprover/lean4/pull/1591 is merged.
