### ISSUE TITLE
Lean3 Type info widget is still nicer

### ISSUE THREAD

**Issue by lovettchris** [leanprover/vscode-lean4#252]
I like this lean3 popup, with extra widgets on it, should we do the same in Lean4 extension?

![image](https://user-images.githubusercontent.com/18707114/193136269-a5b2ec13-9ec3-40a8-a8b4-b25724658a51.png)

**Comment by Vtec234** [comment]
Which features of the lean3 popups would you like to have specifically? The `×` button is just click-out-anywhere now, and go-to-def works on `InteractiveCode` expressions in general. The one button we don't have is "copy to clipboard", which might indeed be useful. I don't have a good idea of how many people use it, though (I never do, personally).

**Comment by lovettchris** [comment]
Ok, fair enough, you are right we have a better goto definition story with Ctrl+hover, but I worry it is not very discoverable.  Perhaps we can hold off until we can think of even more useful buttons to put in there.

**Comment by Vtec234** [comment]
> but I worry it is not very discoverable

The basic idea is that actions which work in the editor should also work in the infoview (so ideally you don't even have to think about it, as it "just works"), but you are right this may not always be obvious, especially coming from Lean 3. We could better highlight this feature in the tutorials/documentation.
