### ISSUE TITLE
Infoview broken after jump to definition

### ISSUE THREAD

**Issue by semorrison** [leanprover/vscode-lean4#254]
Whenever I use <kbd>F12</kbd> to jump-to-definition, the infoview for that file fails with the error

```
Error updating: Error fetching goals: TypeError: Cannot read properties of undefined (reading 'length'). Try again.
```

Unfortunately this somehow then taints that file, and the infoview fails for that file even after I close it and reopen the file directly. (Similarly after re-installing `vscode-lean4` and/or restarting VS Code.)

Possibly related, when I use jump-to-definition the tab bar and the breadcrumb bar both display the filename all in lowercase. (Although when I close and reopen the file directly it is correctly cased.)

This is all on mac os, using `vscode-lean4` at v0.0.95.

Initially reported at https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/.60Cannot.20read.20properties.20of.20undefined.60.

**Comment by semorrison** [comment]
Possibly related https://github.com/microsoft/vscode/issues/55827?

**Comment by gebner** [comment]
Are you starting to see this just now, or was this always broken?  If it used to work, then it would super helpful if you could bisect the regression.

**Comment by semorrison** [comment]
I first noticed it 4 days ago. I'm happy to try bisecting, but I'm not sure what I should bisect on: lean4? vscode-lean4? mathlib4??

**Comment by semorrison** [comment]
(Over on Zulip there is a report that Leo has experienced something similar on mac os + emacs, so this issue may be in the wrong place.)

**Comment by gebner** [comment]
If you're bisecting, I'd try different Lean versions first.  The last vscode-lean4 release is a month old.

**Comment by semorrison** [comment]
Ugh, trying to make a minimal example I can bisect with, I'm finding that the problem seems to be specific to using `F12` to jump to definition into `Std4`. Jumping to definition within the same project (or indeed between two mini projects I set up to test) is working fine, but nothing from any projects into `Std4` is working.

**Comment by lovettchris** [comment]
was this fixed by https://github.com/leanprover/lean4/pull/1701 ?

**Comment by semorrison** [comment]
Not having experienced this in some time, I think we can probably close.

**Comment by mhuisi** [comment]
I am closing this for now and will re-open it if this pops up again somewhere.
