### ISSUE TITLE
large docstrings on type info are too big

### ISSUE THREAD

**Issue by EdAyers** [leanprover/vscode-lean4#256]
Having docstrings in the type info hover in the infoview is nice, but they can take up a lot of space, eg hovering over `=` will generate a huge popup. 

Please could we truncate the rendered docstrings to just be the first paragraph or first 140 chars?

![image](https://user-images.githubusercontent.com/5064353/194513273-60870a37-8f43-441a-9f20-7797bfc31094.png)

**Comment by gebner** [comment]
I thought the plan here was to set a maximum height and make them scrollable.

**Comment by Vtec234** [comment]
See also #210 .

**Comment by EdAyers** [comment]
Closing as duplicate of #210
