### ISSUE TITLE
Hypothesis filter enhancements

### ISSUE THREAD

**Issue by gebner** [leanprover/vscode-lean4#266]
- Inaccessible hypothesis should be filtered out when they're mixed with accessible ones
```lean
example (x x : Nat) :=
  _ -- filtering inaccessible hypotheses should result in `x : Nat` not in `x✝ x : Nat`
```
- Add option to filter out let-values

**Comment by gebner** [comment]
We're still missing the let-values feature request.

**Comment by Vtec234** [comment]
@gebner oops, I missed that! Thanks.
