### ISSUE TITLE
Large popups are clipped

### ISSUE THREAD

**Issue by gebner** [leanprover/vscode-lean4#280]
```lean
def N : Nat := Nat.add 37 50

example : N ≠ N := by
  simp (config := {decide := false}) only [N, Nat.add]
  /- Put cursor on first `Nat.succ` in infoview -/
  sorry
```

The popup will start above and outside of the page, so you can't see where it begins.

![image](https://user-images.githubusercontent.com/313929/213806615-3e173d46-b0a9-4b2c-8dea-0e1c710d3bca.png)

**Comment by tnaoi** [comment]
I tried implementing a fix for this issue using floating-ui instead of popper2. Please let me know if you see any issues with the behavior of the tooltip.

![input mov](https://user-images.githubusercontent.com/10223519/224818022-75d1eb35-f746-4880-b7a8-056fb0165cd5.gif)

**Comment by gebner** [comment]
@tnaoi Please open a PR, this is impossible to evaluate from a screenshot.

**Comment by tnaoi** [comment]
Ah okay, will do that.
