### ISSUE TITLE
installation instructions give error

### ISSUE THREAD

**Issue by miguel-negrao** [leanprover/vscode-lean4#288]
After following the installation instructions from a clean slate (no elan, no lean), I get this error:

![imagem](https://user-images.githubusercontent.com/382777/225020468-90554c8d-5a05-47b9-a74c-ca695a3e1afb.png)

**Comment by tnaoi** [comment]
@miguel-negrao The documentation most likely needs updating since the Lake implementation has changed. You need to use `versionString` instead of `leanVersionString`.

**Comment by miguel-negrao** [comment]
> @miguel-negrao The documentation most likely needs updating since the Lake implementation has changed. Try using `versionString` instead of `leanVersionString`.

That works yes. @semorrison thanks for fixing.
