### ISSUE TITLE
Infoview tweaks to clarify goal list

### ISSUE THREAD

**Issue by hrmacbeth** [leanprover/vscode-lean4#299]
I have noticed, watching novices, that their eyes often move right past the first goal and settle on a later one.  Honestly, I sometimes have this problem too -- I think the infoview is not yet as visually clear as the Lean 3 infoview was.  Here are several tweaks which could help with this problem:
- [X] #285, the suggestion to show a "number of goals" count (this was done in Lean 3)
- more whitespace between the goals
- an option to turn off the titles of the goals ("case: inl.inr" or whatever) -- the tradeoff between visual clutter and information for these titles is often not worth it
- an option to give visual emphasis to the first goal (coloured background? larger font?)
- an option to hide the "expected type" by default (this is a quick fix but a more intelligent solution would be https://github.com/leanprover/lean4/issues/2202, to suppress reporting "expected type" in the contexts when it's not useful)

From the [Zulip conversation](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/small.20.2237.20goals.22.20message) where this was discussed, here is a screenshot showing what the infoview currently looks like when there are many goals.
<img width="1440" alt="Screen-Shot-2023-04-25-at-10 38 15-AM" src="https://user-images.githubusercontent.com/25316162/236692917-6efc175b-7148-4b78-994e-de2469650d8b.png">

**Comment by PatrickMassot** [comment]
@gebner @Vtec234 @EdAyers could you clarify whether all the items on Heather's list would indeed be welcomed PRs?

**Comment by Vtec234** [comment]
@PatrickMassot as far as I am concerned, all of them are :) For the potential options, we have a `lean4.infoview` namespace in the settings declared in `vscode-lean4/package.json` that could be used.

**Comment by Vtec234** [comment]
Done in #302.
