### ISSUE TITLE
Copying via menu in infoview does not work

### ISSUE THREAD

**Issue by BoltonBailey** [leanprover/vscode-lean4#311]
In the infoview, I can mouse over expressions and they highlight. If I then right click, there's a dropdown menu, which allows me to cut, copy, or paste. If I try to copy, though, it doesn't copy the expression to my clipboard like I expect.

[Here is a video of the issue](https://youtu.be/txJeFiJC-qc?t=4875)

**Comment by Vtec234** [comment]
In fact everything here is working as expected, it's just that the UI is terrible :) The cut/copy/paste menu is not added by us: it is injected by VSCode. The actions presented there apply to the current text selection, i.e. the blue piecewise rectangular shape you get by dragging your mouse across some text or double-clicking some text. The blue piecewise rectangular (rounded) shape you get by hovering or clicking a Lean expression is entirely distinct - it is a feature of the infoview specifically - and text selection actions don't apply to it. The two ought to be unified somehow, or at least made more consistent.
