### ISSUE TITLE
Lean 4 extension is always activated on Markdown

### ISSUE THREAD

**Issue by rami3l** [leanprover/vscode-lean4#319]
Thanks a lot for making this extension!

However, I have noticed that it responds to `onLanguage:markdown` and forces me to install the nightly Lean 4. This behavior is confusing to me, especially when working on some non-Lean 4 projects...

I understand that this might help with literal programming, but is it possible to have it toggled on just for specific repositories? 🙏

**Comment by mhuisi** [comment]
This should be resolved with #334 in the new version of the extension that is currently pre-released and will be released in full soon.

**Comment by rami3l** [comment]
@mhuisi I just tested the new beta and the problem seems to be gone. Many thanks!
