### ISSUE TITLE
infoview crashes every type error and crashes if multiple files opened

### ISSUE THREAD

**Issue by fedvasu** [leanprover/vscode-lean4#33]
open a lean file
create a type error
               -> shows the type error and 
               -> (> 50% chance)  infoview crashes
                      -> if infoview didn't crash
                             -> fix the type errors
                                      ->(very likely) infoview hangs indefinitely

I have to restart the infoview, to step through code every time I fix an error.

Infoview either hangs of crashes (without recovering even if I restart)

with following error in the output console

Watchdog error: Got unknown document URI (file:///<path-to-lean>/firstProg.lean)
[Info  - 12:46:21 AM] Connection to server got closed. Server will restart.
[Error - 12:46:21 AM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
..........

**Comment by mhuisi** [comment]
Which version of Lean are you using? (`lean --version`)

**Comment by fedvasu** [comment]
This is the version I am using : 

Lean (version 4.0.0-m2, commit 26dda3f63d88, Release)

**Comment by mhuisi** [comment]
Can you try using the nightly version of Lean 4 ([setup via elan](https://leanprover.github.io/lean4/doc/setup.html#basic-setup)) and see if the issue persists? This extension keeps compatibility with the nightly version, not the release/stable version.

**Comment by fedvasu** [comment]
I changed it to nightly, it seems to be working, please give me couple days to fully test it out before you close this issue.

**Comment by lovettchris** [comment]
Couple days have passed :-)
