### ISSUE TITLE
RFC: jump to definition in context menu in infoview

### ISSUE THREAD

**Issue by semorrison** [leanprover/vscode-lean4#374]
### Proposal

Currently in the infoview one can jump to definition using `ctrl`-left-click (`cmd`-left-click on mac).

However it is hard to discover this.

Could we add `jump to definition` in the right click context menu?

### Community Feedback

Raised in [zulip](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/Go.20to.20definition.20in.20infoview/near/405823117) discussion.

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/vscode-lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others benefit from the changes in this proposal being added, please ask them to add :+1: to it.

**Comment by mhuisi** [comment]
A possible way to implement this: https://code.visualstudio.com/api/extension-guides/webview#context-menus

**Comment by mhuisi** [comment]
This was added in #408.
