### ISSUE TITLE
Restore `fullRange` handling

### ISSUE THREAD

**Issue by Kha** [leanprover/vscode-lean4#392]
The language server reports diagnostics with a custom `fullRange` field that defines an extended range where the message should be considered "active" by the info view without being highlighted in the editor. This is absolutely crucial for e.g. working with indentation-based tactics. Unfortunately, the handling code seems to have been lost in a refactoring:
before: https://github.com/leanprover/vscode-lean4/pull/30/files#diff-a5cd783b2942aa4bce645a2be9e41bbdbc782a2a545d5523046ef4889333b19cL73 (unfold `infoview/messages.ts`)
after: https://github.com/leanprover/vscode-lean4/pull/30/files#diff-f3205301d3c8487365c663b3f0147c3cb14360f4d68f4409554ad27328c56025R118

Broken example:
```
example : False := by
  apply id
  apply id  -- goal moved to "All Messages"
```
(not sure why it works on the first `apply`, might be a off-by-one in either the server or the client)

**Comment by Vtec234** [comment]
Hah, so that's what that field was for! This is technically documented [here](https://github.com/leanprover/lean4/blob/0055baf73a00c913f08d9cbf7a076c936c029707/src/Lean/Data/Lsp/Diagnostics.lean#L93), but I had no idea what it meant operationally until seeing the explanation above.
