### ISSUE TITLE
Failed to start lsp on leanprover/lean4

### ISSUE THREAD

**Issue by wasd96040501** [leanprover/vscode-lean4#395]
### Description

Failed to start lsp on leanprover/lean4
lsp output:
```
/data00/home/luoyangze.ptrl/lean/lean4/src> lean +lean4-stage0 --version
info: downloading component 'lean'

Error(Download(HttpStatus(404)), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })

error: could not download nonexistent lean version `lean4-stage0`
info: caused by: could not download file from 'https://github.com/leanprover/lean4/releases/expanded_assets/lean4-stage0' to '/home/luoyangze.ptrl/.elan/tmp/_nkj58izxgex6f85_file'
info: caused by: http request returned an unsuccessful status code: 404

=> Operation failed. Exit code: 1.
/data00/home/luoyangze.ptrl/lean/lean4/src> lean +lean4-stage0 --version
info: downloading component 'lean'

Error(Download(Msg("error during download")), State { next_error: Some(Error { description: "Timeout was reached", code: 28, extra: Some("Failed to connect to github.com port 443 after 15233 ms: Couldn't connect to server") }), backtrace: InternalBacktrace { backtrace: None } })

error: could not download file from 'https://github.com/leanprover/lean4/releases/expanded_assets/lean4-stage0' to '/home/luoyangze.ptrl/.elan/tmp/nrlqow9c3iavjxp8_file'
info: caused by: error during download
info: caused by: [28] Timeout was reached (Failed to connect to github.com port 443 after 15233 ms: Couldn't connect to server)

=> Operation failed. Exit code: 1.
```
run in commandline
```
> lean +lean4-stage0 --version                                       
info: downloading component 'lean'
Error(Download(HttpStatus(404)), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })
error: could not download nonexistent lean version `lean4-stage0`
info: caused by: could not download file from 'https://github.com/leanprover/lean4/releases/expanded_assets/lean4-stage0' to '/home/luoyangze.ptrl/.elan/tmp/7gyehgrhaon28r39_file'
info: caused by: http request returned an unsuccessful status code: 404
```

### Steps to Reproduce

1. just open downloaded leanprover/lean4 folder

**Expected behavior:** [Clear and concise description of what you expect to happen]
Lsp start successfully

**Actual behavior:** [Clear and concise description of what actually happens]
Lsp not work, cannot goto def etc...

### Versions

[Version of vscode-lean4 (Hover over 'lean4' in the 'Extensions' menu)]  
v0.0.127
[Output of `lean --version` in the folder that the issue occured in]  
Lean (version 4.5.0, commit 1a3021f98e55, Release)
[OS version]
debian 10

### Additional Information

[Additional information, configuration or data that might be necessary to reproduce the issue]

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/vscode-lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by Kha** [comment]
You need to follow the complete [development setup](https://lean-lang.org/lean4/doc/dev/index.html) in order to interact with the lean4 source repo.
