### ISSUE TITLE
Support `${workspaceFolder}` and similar variables in `lean4.toolchainPath`

### ISSUE THREAD

**Issue by eric-wieser** [leanprover/vscode-lean4#400]
I have a multi-root workspace that includes a modified version of Lean, something like:

* `/`
  * `tools/`:
    * `lean`: this repo
  * `projects/`:
    * `foo` (a lean project)
    * `extra/`
      * `bar` (a lean project)

I'd like to set `lean4.toolchainPath` workspace-wide, but either:
* I use absolute paths, and they break on another user's machine
* I use a relative path, which is treated as relative to each folder separately and so doesn't work unless all the project root folders are at the same nesting.

If vscode-lean4 used https://www.npmjs.com/package/vscode-variables, then I could use
```json
   "lean4.toolchainPath": "${workspaceFolder}/my_lean/.../
```
and things would be behave as expected.

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/vscode-lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others benefit from the changes in this proposal being added, please ask them to add :+1: to it.

**Comment by mhuisi** [comment]
We want to remove this setting in the future. Is there another way that you can set up the project to use your modified version of Lean? (E.g. using Elan or your lean-toolchain file)

**Comment by eric-wieser** [comment]
If `lean-toolchain` could allow a relative path, that would also work for me.

The current `elan override` mechanism doesn't work because it is overridden by the `lean-toolchain`, while the current `elan toolchain link` doesn't work because it is globally scoped, so it is not possible to have two checkouts of my workspace on the same computer and use them in parallel.

**Comment by Kha** [comment]
> If `lean-toolchain` could allow a relative path, that would also work for me.

Contributions welcome by the way :)

**Comment by mhuisi** [comment]
I assume hosting the modified version of Lean in a public GitHub repository and referring to that in your `lean-toolchain` is not an option (e.g. because the project is private)? 

To be clear, I consider this to be an Elan issue. `lean4.toolchainPath` should never be used for any serious project setups. It's a quick and dirty hack intended for debugging.

**Comment by Kha** [comment]
> Isn't it currently used by lean itself?

No, we use `toolchain link`

**Comment by eric-wieser** [comment]
Ah, so does that mean it's not currently possible to have two configured checkouts of different branches of the Lean4 repository on the same computer?

**Comment by mhuisi** [comment]
> Is the intent for the extension to not know about toolchains at all in future

We certainly want to move more in this direction, but there's still a couple of features that will need to rely on the toolchain version, unfortunately.
