### ISSUE TITLE
Querying Lean Status Information from Terminal

### ISSUE THREAD

**Issue by JianqiaoLu** [leanprover/vscode-lean4#403]
I'm currently exploring the capabilities of Infoview in Lean, where it allows me to directly observe the Lean status of each .lean file, including aspects like grammar errors or the output from #check. I'm interested in finding a way to extract this information through a terminal command. Specifically, I'm looking to retrieve details on grammar errors and the results from #check commands in my .lean files via the terminal.

Could anyone guide me on how to achieve this? Any pointers or commands that could help me access this Lean status information from the terminal would be greatly appreciated.

Thank you!

**Comment by Kha** [comment]
Please use https://leanprover.zulipchat.com for questions about Lean
