### ISSUE TITLE
Keyboard shortcut \<- for `←` not working

### ISSUE THREAD

**Issue by thorimur** [leanprover/vscode-lean4#409]
### Description

The hover on `←` says that <kbd>\\</kbd><kbd><</kbd><kbd>-</kbd> is a valid keyboard shortcut for it (and is one that I personally have muscle memory for), but it's overtaken by the (also very nice) new autoclosing behavior for angle brackets introduced by #405.

### Steps to Reproduce

1. Type <kbd>\\</kbd><kbd><</kbd><kbd>-</kbd><kbd>space</kbd>

**Expected behavior:** `← ` is inserted

**Actual behavior:** `⟨- ⟩` is inserted

### Versions

v0.0.130 
4.7.0-rc1
macOS

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/vscode-lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by thorimur** [comment]
One fix for this is of course "remove the `\<-` keyboard shortcut", but I wonder: is it possible to have VS Code somehow consider `⟨-` a keyboard shortcut for `←`? Though I suppose deletion of `⟩` would need to be handled somehow, which that PR's description seems to indicate is difficult.

**Comment by mhuisi** [comment]
Ah. That's very unfortunate. I will revert the change since this affects lots of other abbreviations as well.
