### ISSUE TITLE
RFC: GUI button to download cache for a specific file

### ISSUE THREAD

**Issue by YaelDillies** [leanprover/vscode-lean4#416]
### Proposal

Oftentimes I want to work on a rather low-level file `X`. `lake exe cache get` would download me way too many files and take too long, but typing `lake exe cache get Mathlib/X.lean` (where `X` is a long file path) is also quite unergonomic.

I suggest we add a pretty visible button on the file window to download cache for the file currently in focus.

### Community Feedback

[Zulip](https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/Get.20cache.20for.20a.20specific.20file)

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/vscode-lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others benefit from the changes in this proposal being added, please ask them to add :+1: to it.

**Comment by arthurpaulino** [comment]
If there's a file in focus that doesn't have its current `olean` up to date, I assume there will be work happening in the background. Won't the background job conflict with what the user tries to do when summoning `cache`? Or was this issue resolved?

**Comment by YaelDillies** [comment]
oleans now get rebuilt only if the user explicitly asks for it. Does this answer your question?

**Comment by arthurpaulino** [comment]
Yeap, thanks!

**Comment by YaelDillies** [comment]
🏓 This feature would save me 10-15min a day, so I really want it.
