### ISSUE TITLE
import Foo.αβγ doesn't work on Windows

### ISSUE THREAD

**Issue by lovettchris** [leanprover/vscode-lean4#43]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

Windows can't find the file named "αβγ .lean" in the folder named "Foo", so the utf-8 support needs to also be moved to vscode somehow and to leanpkg.exe...

### Steps to Reproduce

[bug.tar.gz](https://github.com/leanprover/vscode-lean4/files/7261965/bug.tar.gz)

1. Load attached into vscode on windows

**Expected behavior:** 

it should work fine, "leanpkg build" on Linux works fine.

**Actual behavior:** 

`leanpkg print-paths` failed:
```
stderr:
configuring Foo 0.1
no such file or directory (error code: 2)
  file: .\Foo\a߿.lean
```

**Reproduces how often:** 

100%

### Versions

master c586f9d0b6cc519b8a96807c31435a6a8f0acb10

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by gebner** [comment]
If `leanpkg print-paths` fails already then this is a bug in core Lean 4, and we can't do anything about it in the vscode extension.

**Comment by lovettchris** [comment]
I think you might be right.  print-paths doesn't fail:

d:\Temp\lean_examples\bug>leanpkg print-paths
configuring Foo 0.1
.\.\build
.\.
```

but the build does:
```
d:\Temp\lean_examples\bug>leanpkg build
configuring Foo 0.1
no such file or directory (error code: 2)
  file: .\Foo\╬▒╬▓╬│.lean
```

**Comment by leodemoura** [comment]
> If `leanpkg print-paths` fails already then this is a bug in core Lean 4, and we can't do anything about it in the vscode extension.

Correct. It is related to 
https://github.com/leanprover/lean4/issues/698
