### ISSUE TITLE
Initial version check does not use `lean` executable from `lake`

### ISSUE THREAD

**Issue by llllvvuu** [leanprover/vscode-lean4#440]
### Description

If only `lake` is on the path but not `lean`, and `"lean4.lakePath"` is defined but `"lean4.toolchainPath"` is not, then the extension will not start. The workaround is to run "Lean 4: Server: Restart Server".

### Context

When initializing the client, it checks the version:
https://github.com/leanprover/vscode-lean4/blob/8205219699aedd6bd6a8a07a6a8cce1ae4752039/vscode-lean4/src/utils/clientProvider.ts#L297-L301

and does not start the client if the version is not found here:
https://github.com/leanprover/vscode-lean4/blob/8205219699aedd6bd6a8a07a6a8cce1ae4752039/vscode-lean4/src/utils/clientProvider.ts#L353-L361

`getLeanVersion` only accounts for PATH and toolchainPath but not lake:

https://github.com/leanprover/vscode-lean4/blob/8205219699aedd6bd6a8a07a6a8cce1ae4752039/vscode-lean4/src/utils/leanInstaller.ts#L182-L188

If neither are set (i.e. only `lake` is on the path), then the client will not start. "Restart Server" works fine, since that code path uses:

https://github.com/leanprover/vscode-lean4/blob/8205219699aedd6bd6a8a07a6a8cce1ae4752039/vscode-lean4/src/leanclient.ts#L568-L570

### Steps to Reproduce

1. Install lake and lean somewhere not on $PATH.
2. Set "lean4.lakePath"
3. Open a .lean file.

**Expected behavior:** The client starts.

**Actual behavior:** The client does not start.

### Versions

HEAD ([8205219](https://github.com/leanprover/vscode-lean4/commit/8205219699aedd6bd6a8a07a6a8cce1ae4752039))

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/vscode-lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by mhuisi** [comment]
Why are you using these configuration settings in the first place?
