### ISSUE TITLE
RFC: better name for `Docview: Open docview`

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/vscode-lean4#444]
### Proposal

In the VSCode extension, when pressing the extension icon you can go to the documentation books by pressing `∀ > Documentation ... > Docview: Open docview`.
Can we rename the last command `Docview: Open docview` to something more beginner-friendly, e.g. `Show documentation`?

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others benefit from the changes in this proposal being added, please ask them to add :+1: to it.

**Comment by mhuisi** [comment]
The name of this command has been changed to "Docs: Show Documentation Resources" in #473.

**Comment by ReubenkThomas** [comment]
This may be the wrong place to put this, but I can't open up HTML pages like "Mathematics in Lean" using this method. Is this a bug or is there another way to open the doc?

**Comment by mhuisi** [comment]
> This may be the wrong place to put this, but I can't open up HTML pages like "Mathematics in Lean" using this method. Is this a bug or is there another way to open the doc?

Support for reading the content of `html` folders was already removed a couple of months ago. Currently, you'll need to read the online version of the book using the `Show Documentation Resources` command. We'll re-add some variant of a feature to read local docs in the future when adding tighter VS Code for [Verso](https://github.com/leanprover/verso).
