### ISSUE TITLE
Code actions, to "fill holes" with suggestions from Lean Language Server

### ISSUE THREAD

**Issue by lovettchris** [leanprover/vscode-lean4#45]
Need server to provide nice text spans so there's no regex hackery...
From the Lean3 vscode extension readme:
```
Fill in {! !} holes (also _ holes in Lean 3.16.0c and later) with the code actions menu (ctrl+.)
Tactic suggestions (tactics which suggest edits with a "Try this:" message) can be applied either with a keyboard shortcut (alt+v), by clicking on the info view message, or via code actions (ctrl+.)
```
the syntax is a bit weird though... (from idris) can we do it without magic syntax?

**Comment by GetContented** [comment]
Will this also allow us to get agda/idris style case splitting?

**Comment by Vtec234** [comment]
These are now in leanprover/std4#132.
