### ISSUE TITLE
Search for declarations in open files (ctrl+t)

### ISSUE THREAD

**Issue by lovettchris** [leanprover/vscode-lean4#46]
lean4 server needs to add this.

**Comment by leodemoura** [comment]
@lovettchris Could you please describe the required changes on the Lean LSP server?

**Comment by Kha** [comment]
By building on top of @Garmelon's work when that is ready, it should be straightforward to support this even for closed files - with the same approximation properties, most likely "state from the last successful full build".

**Comment by Kha** [comment]
Duplicate of leanprover/lean4#396
