### ISSUE TITLE
hover in infoview broke in 0.0.156

### ISSUE THREAD

**Issue by llllvvuu** [leanprover/vscode-lean4#461]
Opened a fix at #462 

### Description

>  I now only see the message "Error: no position context set" when I hover over something in the infoview.

### Context

https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/Error.3A.20no.20position.20context.20set/near/442619247

### Steps to Reproduce

1. Update to 0.0.156
2. Open a Lean file with contents `example (issue461 : Type 4) : issue461 := by sorry`
3. Click on `by`
4. Hover over `issue461` in the goal in the infoview.

**Expected behavior:** `issue461 : Type 4`

**Actual behavior:** `Error: no position context set`

### Versions

0.0.156
Lean (version 4.8.0-rc2, aarch64-apple-darwin, commit 873ef2d894af, Release)

### Additional Information

Looks like this broke in #449. `<Info />` lacks the new `<EnvPosContext />`.

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/vscode-lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by mhuisi** [comment]
This was ultimately resolved by #464.
