### ISSUE TITLE
RFC: indicator for out of date infoview

### ISSUE THREAD

**Issue by hargoniX** [leanprover/vscode-lean4#470]
### Proposal
Show some form of indicator for when the goal state that's currently being presented in the info view is out of date / being recomputed.

  - **User Experience**: Users can clearly judge when the information they are being presented is current. With recent features such as incrementality or the planned feature to show goals before the entire proof was elaborated this type of information becomes more important.

  - **Beneficiaries**: People that write large proofs on Lean releases with incrementality etc. know precisely when the information they are looking at is out of date/up to date.

  - **Maintainability**: Unclear.
 

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/vscode-lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others benefit from the changes in this proposal being added, please ask them to add :+1: to it.

**Comment by Vtec234** [comment]
Have you noticed that a yellow tint appears on the location (`myfile.lean:12:34`) when it is loading? Are you requesting a more prominent indication?

**Comment by hargoniX** [comment]
I do think a more prominent indication would be sensible yes. I talked to a few users and none of them (including myself) even noticed that this feature exists, let alone its meaning.
