### ISSUE TITLE
Overview missing in VSCode Marketplace

### ISSUE THREAD

**Issue by bryangingechen** [leanprover/vscode-lean4#493]
### Description

[The lean4 extension page on the VS Code marketplace](https://marketplace.visualstudio.com/items?itemName=leanprover.lean4) says: No overview has been entered by publisher.

Here's what it looks like when searching from within VS Code:

![Screenshot 2024-07-02 at 18 38 12](https://github.com/leanprover/vscode-lean4/assets/5209952/a19c7b4a-3cac-4434-a898-d54a80faff44)

I'm guesssing the main README file from this repo would be suitable as an overview for the extension, but the file isn't being included in the .vsix file that is being published.

**Expected behavior:** The README file from this repo appears.

**Actual behavior:** See above.

### Impact

People might be suspicious of an extension with a blank overview.

Add :+1: to [issues you consider important](https://github.com/leanprover/vscode-lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by mhuisi** [comment]
We have a new README that refers to the setup guide and the manual now and it is displayed in the VS Code marketplace.
(#501, #502, #503)
