### ISSUE TITLE
RFC: Remove character '﷼' from abbreviations

### ISSUE THREAD

**Issue by adomasbaliuka** [leanprover/vscode-lean4#522]
### Proposal

We are considering adding a linter to Mathlib (https://github.com/leanprover-community/mathlib4/pull/16215) that checks all unicode characters against a whitelist.

Since the character '﷼': Unicode U+FDFC (category Sc: Symbol, currency)

is currently not used in Mathlib and expects right-to-left text flow, we would disallow it

. (E.g., consider this code, which is currently allowed in Lean (note the meaning of "infix"):

```lean
infix:50 " ﷼ " => Add.add
def x :=
  2 ﷼ 2

```

For consistency, all characters in the abbreviations JSON should be allowed by the linter. 

Could we remove it from the abbreviations set [here](https://github.com/leanprover/vscode-lean4/blob/97d7d8c382d1549c18b66cd99ab4df0b6634c8f1/lean4-unicode-input/src/abbreviations.json#L1122)?

@PatrickMassot advocated for this at [Zulip](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/Whitelist.20for.20Unicode.3F/near/465755127)

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/vscode-lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others benefit from the changes in this proposal being added, please ask them to add :+1: to it.

**Comment by adomasbaliuka** [comment]
Update: the linter has been merged to Mathlib, see https://github.com/leanprover-community/mathlib4/pull/36773
The following characters that have abbreviations were disallowed:

- '\u2001', -- \quad (U+2001) (due to being non-standard whitespace)
- ~~'\uFDFC', -- RIAL sign (U+FDFC) (due to triggering right-aligned text).~~ (Already removed from extension in https://github.com/leanprover/vscode-lean4/pull/525))
- '\u060B', -- AFGHANI sign (U+060B) (due to triggering right-aligned text)
- '\u0332' -- COMBINING LOW LINE (U+0332) (due to modifying characters around it)

**Comment by mhuisi** [comment]
> Update: the linter has been merged to Mathlib, see [leanprover-community/mathlib4#36773](https://github.com/leanprover-community/mathlib4/pull/36773) The following characters that have abbreviations were disallowed:
> 
>     * '\u2001', -- \quad (U+2001) (due to being non-standard whitespace)
> 
>     * ~'\uFDFC', -- RIAL sign (U+FDFC) (due to triggering right-aligned text).~ (Already removed from extension in [chore: remove rial symbol #525](https://github.com/leanprover/vscode-lean4/pull/525)))
> 
>     * '\u060B', -- AFGHANI sign (U+060B) (due to triggering right-aligned text)
> 
>     * '\u0332' -- COMBINING LOW LINE (U+0332) (due to modifying characters around it)

#764
