### ISSUE TITLE
Enhancement suggestion: Tool-tips causing visibility issues, use key-press to enable

### ISSUE THREAD

**Issue by rzeta0** [leanprover/vscode-lean4#559]
### Description

The tooltips can be large, and too often hide what you're reading, editing, or wanting to inspect via Infoview.

Disabling them entirely is an option, but an enhancement would be to enable them with a conscious act, eg a key-press.

This is a UX and accessibility issue.

### Versions

Extension Lean 4  v0.0.186 
VSC Version: 1.96.0
MacOS 15.2

### Additional Information

Attached is a screenshot illustrating the problem:

![Screenshot 2024-12-17 at 19 58 00](https://github.com/user-attachments/assets/eefff28f-f7da-4e65-81da-15157e5ee5a5)

### Suggestion

Add options to allow a key-press eg Shift to bring up a hovering tooltip if and only when desired.

This won't break previous behaviour, but will allow those who occasionally benefit from tooltips to easily enable them only for the duration they need them.

**Comment by mhuisi** [comment]
A non-discoverable key press to trigger hovers is a significant UX regression for users who do not study all the key bindings of every editor they use, a deviation from how VS Code behaves normally and how most other IDEs behave, i.e. how most users expect hovers to work. Furthermore, the VS Code editor hover UX is not configurable by extensions beyond the 'Editor › Hover' settings that are already provided by VS Code.

Users that dislike this default behavior can change it using the 'Editor: Hover' and 'Infoview: Show Tooltip On Hover' settings and configure their preferred keyboard shortcut for editor hovers by setting the 'Show or Focus Hover' shortcut (default: `Ctrl+K Ctrl+I`) in VS Code's keyboard shortcut settings.

**Comment by rzeta0** [comment]
You misunderstand. This suggestion will not change behaviour except for those who configure it to do so.

**Comment by mhuisi** [comment]
As mentioned above, these options already exist.
