### ISSUE TITLE
InfoView stops updating afer "Lean 4: Resstart Server" command

### ISSUE THREAD

**Issue by lovettchris** [leanprover/vscode-lean4#58]
Steps:
1. install vscode lean4 extension v0.0.39
1. load a lean4 folder
1. check everything works fine, including the infoview.
1. run `Lean 4: Resstart Server" command`
1. now move caret around the .lean file and check the infoview still works.

Someones you see this output:
```
Watchdog error: cannot find open document 'file:///d%3A/Temp/lean_examples/Foo/Foo.lean'
[Error - 11:57:39 AM] Connection to server got closed. Server will not be restarted.
```
and the infoview stops updating.

I'm wondering if this needs to be re-initialized after client restart since the initializeResult will be different after server restart...
```
await webviewPanel.api.initialize(this.client.initializeResult, this.getLocation(editor))
```

**Comment by Vtec234** [comment]
Looks like this has been fixed in our recent changes. If anyone is still observing the issue, please reopen.

**Comment by lovettchris** [comment]
Agreed
