### ISSUE TITLE
Resurrect tactic state filters

### ISSUE THREAD

**Issue by gebner** [leanprover/vscode-lean4#76]
Provide a way to filter out hypotheses in the tactic state / expected type.  For example:
 * Hide hidden assumptions (i.e., the ones with the dagger)
 * Hide type class instances.
 * Hide types (i.e., assumptions like `α : Type`).
 * Hide the gigantenormous let-values inside do-notation.

Some of that may require additional server support though.

**Comment by gebner** [comment]
We've had a similar filter in the Lean 3 extension, which might be good for inspiration.

**Comment by leodemoura** [comment]
@gebner I am missing this feature too. I am happy to implement the LSP server part. I think @lovettchris can help with the VSCode part. Do you have a design in mind? If yes, could you please share it here?

**Comment by gebner** [comment]
I would have added a couple of flags in `InteractiveHypothesis` on the server side:
```lean
structure InteractiveHypothesis where
  names : Array String
  type : CodeWithInfos
  val? : Option CodeWithInfos := none
  -- new:
  isInstance : Bool
  isType : Bool
  deriving Inhabited, RpcEncoding
```

The filtering then happens here in the extension.  We can just add a dropdown like we had in Lean 3 (or a menu with checkboxes).

In (pre-widget) Lean 3 we also had filtering based on user-provided regexes.  I'm not sure how much people were using that feature, but it can be implemented purely in the extension.

> Hide the gigantenormous let-values inside do-notation.

For this I would first try to use let_fun instead of let in the desugaring.  (Or if that doesn't work because of VM or delaboration issues, a custom let_no_val elaborator that elaborates into a let, but adds a value-less free variable to the local context.)

**Comment by Kha** [comment]
It feels wrong to me that we show `let`s from macros at all. On the other hand, for tactics we do often want to show hygiened local variables, especially when they can be un-hygiened by simply passing a name. Could we turn this around and make only tactic-introduced hygiened fvars visible (by default)? We already have special casing for `tactic.hygiene`, shouldn't these two things coincide?

**Comment by leodemoura** [comment]
@gebner Thanks for the useful feedback.

> For this I would first try to use let_fun instead of let in the desugaring. (Or if that doesn't work because of VM or delaboration issues, a custom let_no_val elaborator that elaborates into a let, but adds a value-less free variable to the local context.)

What about an `Expr.mdata` that instructs the printer to hide the term? That is, we would have a flag that instructs the system to display any term annotated with the `Expr.mdata` as a `...`. It would be great if users had the option to expand this kind of term by clicking `...`. What do you think?

**Comment by leodemoura** [comment]
I am wondering whether it would be useful to have a flag that instructs Lean to display a goal as
```
target 
|-
h_n : A_n
...
h_1 : A_1
```
What do you thing?

**Comment by gebner** [comment]
> What about an `Expr.mdata` that instructs the printer to hide the term? That is, we would have a flag that instructs the system to display any term annotated with the `Expr.mdata` as a `...`.

This is a great idea.  We have something similar in mathlib in Lean 3: https://leanprover-community.github.io/mathlib_docs/tactics.html#elide%20/%20unelide

> It would be great if users had the option to expand this kind of term by clicking `...`. What do you think?

Practically speaking, it would be easier to show it in a popup for now.  (We have no way to reformat expressions client-side, so we can't just paste the expanded version without messing up indentation, etc.)

**Comment by gebner** [comment]
> I am wondering whether it would be useful to have a flag that instructs Lean to display a goal as

This can be trivially implemented in the editor extensions.  I can't say I've ever wanted such an option though.  It doesn't really solve the issue with the huge lets either.

**Comment by gebner** [comment]
> It feels wrong to me that we show lets from macros at all.

I think it would be just as confusing if they were omitted.  They can still occur in other hypotheses and the goal after all.  Tactics like assumption can find them (iirc), they can contribute local type class instances, you also want to know the value of the let-bindings because they might unfold in zeta-reduction.

If I think about the other big local context polluter, the syntax quotation matcher, then half of the introduced lets are (transitively) reachable from the visible hypotheses (and are hence relevant in some sense):
```
x✝ : Syntax
discr✝¹¹ : Syntax := x✝
discr✝¹⁰ : Syntax := Syntax.getArg discr✝¹¹ 0
discr✝⁹ : Syntax := Syntax.getArg discr✝¹¹ 1
discr✝⁸ : Syntax := Syntax.getArg discr✝¹¹ 2
discr✝⁷ : Syntax := Syntax.getArg discr✝⁸ 0
discr✝⁶ : Syntax := Syntax.getArg discr✝⁸ 1
discr✝⁵ : Syntax := Syntax.getArg discr✝⁶ 0
discr✝⁴ : Syntax := Syntax.getArg discr✝⁵ 0
discr✝³ : Syntax := Syntax.getArg discr✝⁵ 1
discr✝² : Syntax := Syntax.getArg discr✝⁵ 2
discr✝¹ : Syntax := Syntax.getArg discr✝⁶ 1
discr✝ : Syntax := Syntax.getArg discr✝⁸ 2
x : Syntax := discr✝²
y : Syntax := discr✝⁴
z : Syntax := discr✝¹⁰
⊢ Int
```

I'd also like to see fewer helper definitions in the local context, but I'm also uneasy if there is hidden state (that I can't see but which still affects tactics).  If we drop lets from macros in tactics as well, then we get questions like "why does `let x := blah; by assumption` only work outside macros?".

**Comment by gebner** [comment]
> > It would be great if users had the option to expand this kind of term by clicking `...`. What do you think?
> 
> Practically speaking, it would be easier to show it in a popup for now. (We have no way to reformat expressions client-side, so we can't just paste the expanded version without messing up indentation, etc.)

We could also just abbreviate all *multi-line* let values by ... in the editor extension.  Then we could easily expand it in-place.

**Comment by leodemoura** [comment]
> > I am wondering whether it would be useful to have a flag that instructs Lean to display a goal as
> 
> This can be trivially implemented in the editor extensions. I can't say I've ever wanted such an option though. It doesn't really solve the issue with the huge lets either.

I was not proposing this issue for the huge let, but for big goals, I have experienced in the past.

**Comment by Kha** [comment]
> They can still occur in other hypotheses and the goal after all.

Then we should definitely show them. The syntax match should indeed use let_fun there if possible.

> Tactics like assumption can find them (iirc)

True, but is it reasonable?

```
macro "ohmy" : tactic => `(intro x)

example (p : Prop) : p → p := by
  ohmy
  assumption
```
This is very similar to the `exact x` example we have in our macro paper that we call undesirable.

> they can contribute local type class instances

Yes, we should not hide assumptions of type class types

**Comment by Kha** [comment]
> This is very similar to the `exact x` example we have in our macro paper that we call undesirable.

Ah, but there is probably no way to fix that without also disallowing access to "merely unnamed" hypotheses... still, we could disallow `assumption` to resolve to non-tactic introduced hygiened assumptions if we introduce such a marker.

**Comment by lovettchris** [comment]
I'm only following about 10% of this conversation, can someone provide some Lean samples I can play with to see how bad the problem is, and what exactly you want to hide in the infoview with expandable [...]'s ?

**Comment by lovettchris** [comment]
Leo provided me with this example: https://github.com/lovettchris/lean4/blob/master/tests/playground/pge.lean#L272 which is plenty big :-)  The `p_def` and `-q_def` terms in the Tactic state are particularly verbose...

**Comment by lovettchris** [comment]
Here's one simple change the provide one of the things Leo wanted - an easy way to reverse the order of the lists, see https://github.com/leanprover/vscode-lean4/pull/177

**Comment by lovettchris** [comment]
> It wasn't deprecated. It was hard to implement with the new widgets approach, so it never got ported. I'm not sure if anybody needs more flexibility than the provided set of filters though.

how would you feel if I removed the user defined [infoViewTacticStateFilters](https://github.com/leanprover/vscode-lean/blob/master/package.json#L116) settings for now (one less thing to maintain) ?

**Comment by gebner** [comment]
Maybe it's best to remove it for now, as the settings does not have any effect.  Come to think of it, we have quite a few settings that we could clean up.

**Comment by lovettchris** [comment]
@Kha, @leodemoura, @gebner , Ok, with the above PR complete, this leaves the one remaining suggestion here of "Hide the gigantenormous let-values inside do-notation."

There was lots of discussion from Expr.mdata which was popular but I'm not sure I see a proposed solution for gigantenormous let-values?

**Comment by leodemoura** [comment]
> @Kha, @leodemoura, @gebner , Ok, with the above PR complete, this leaves the one remaining suggestion here of "Hide the gigantenormous let-values inside do-notation.". The p_def and q_def are also really big in https://github.com/lovettchris/lean4/blob/master/tests/playground/pge.lean#L272, are those considered let-values?
> 
> There was lots of discussion from Expr.mdata which was popular but I'm not sure I see a proposed solution for gigantenormous let-values?

@gebner I am happy to add `elide`/`unelide` tactics to Lean 4. I can also add a tactic for "eliding" big `let`-values. What else do we need for "Hide the gigantenormous let-values inside do-notation."?

**Comment by leodemoura** [comment]
@lovettchris You can use the following file to experience the "gigantenormous let-values"  
https://github.com/leanprover/lean4/blob/master/tests/lean/run/do_eqv.lean
Here is the content of the infoview for the line marked with `-- HERE`
![image](https://user-images.githubusercontent.com/2778936/171299166-28b25646-44bd-46b9-b492-a4622fb250d6.png)

**Comment by lovettchris** [comment]
Thanks, yeah I see it, both the goal and the hypothesis are huge, it also seems to be some sort of expanded and inverted form of the code I see here:
```lean
    (do for xs in xss do
           for x in xs do
             let b ← p x
             if b then
               return some x
        return none)
```
as a noob it does seem a bit silly to me to just pretty print back so much code.  The goal can't really be that hard to complete given it was completed by:
```lean
    induction xs with simp
    | cons x xs ih =>
      apply byCases_Bool_bind <;> simp [ih]
```

**Comment by gebner** [comment]
> What else do we need for "Hide the gigantenormous let-values inside do-notation."?

Just to clarify, I meant the issue with big lets *inside* do-notation.  The example you've posted is a huge pretty-printed term when proving something about do-notation.  I don't think there's much we can do about that.  If you want to prove something about a huge and ugly term, then you need to see the huge and ugly term.

What I meant though is this:
```lean
def big : IO Unit := do
  if true then
    IO.println "a"
    --^ check expected type here
  if false then
    IO.println "b"
  if 1 < 3 then
    IO.println "c"
```

At the first print statement there's a huge `_do_jp` assumption in the local context.  This affects just the goal display (but not error messages, I guess we filter out inaccessible assumptions inconsistently).  As far as I can see, we have already mentioned several possible solutions in this thread:

 1. Hide multi-line let-values in the editor extension.  (Technically feasible, but work is duplicated for every editor, and might have collateral damage)
 2. Use `let_fun` in do-notation, or clear the `_do_jp` assumption.
 4. Hide some inaccessible assumptions.  (But I don't think we have a clear proposal on which ones to hide.  Some like `stx† : Syntax` should probably be elided (if they have no forward dependencies).  Others like `inst† : Inhabited R` should remain visible, even if they're not referenced anywhere.  And then there's the question if `contradiction` should find `h† : False`.)

> I am happy to add `elide`/`unelide` tactics to Lean 4. I can also add a tactic for "eliding" big `let`-values. 

I think `elide` by itself is really low priority (nobody uses it in mathlib).  Requiring users to run a tactic first won't help with the goals in do-notation either.  It would only make sense if the `_do_jp` let-values were automatically elided.

**Comment by lovettchris** [comment]
@gebner, Thanks for the clarifying sample!

I think "Expected types" are useful, but why does `IO.println` have an expected type of `_do_jp✝` ?  Or is this just an internal detail of how "do" notation is implemented?  Unfortunately goto-definition doesn't work on the "do" keyword.  But is there a way to change the "do" implementation to hide this internal detail from the pretty printed expected type info, perhaps that implementation could use Leos proposed elide feature?

**Comment by leodemoura** [comment]
The commit above addresses the `_do_jp` issue. Now, when we display the expected type in the info view, an inaccessible declaration is only displayed when the expected type depends on it. I think it makes sense to only display the information when it is relevant.

**Comment by Vtec234** [comment]
> > What about an `Expr.mdata` that instructs the printer to hide the term? That is, we would have a flag that instructs the system to display any term annotated with the `Expr.mdata` as a `...`.
> > It would be great if users had the option to expand this kind of term by clicking `...`. What do you think?
> 
> Practically speaking, it would be easier to show it in a popup for now. (We have no way to reformat expressions client-side, so we can't just paste the expanded version without messing up indentation, etc.)

A bit late to the discussion, but we could set a `pp` option using `OptionsPerPos` at the `mdata` location (already known client-side since we started passing the position in `SubexprInfo`) which expands the `...`. It would require relaborating the entire expression, but for expressions which fit on a single page this should not be excessive overhead.

**Comment by gebner** [comment]
If it's just for elide, then I don't think implementing reformatting is worth the trouble.  You can implement the popup version without even touching core:
```lean
import Lean
open Lean PrettyPrinter Delaborator SubExpr

elab "⋯" elided:(term)? : term <= expectedType =>
  return mkAnnotation `elide
    (← Elab.Term.elabTerm (elided.getD (← `(_))) expectedType)

@[delab mdata]
def delabElide : Delab := do
  let some e := annotation? `elide (← getExpr) | failure
  if ← getPPOption getPPAll then
    -- in the popup (for a less hacky version call `failure` if `pp.explicit` is set)
    withMDataExpr do withOptionAtCurrPos `pp.all false do
      delab
  else
    `(⋯)

#check ⋯ 42
```

**Comment by lovettchris** [comment]
I talked with Gabriel, he agreed, what we have no is good, we can add more specific features later as needed, but this work item can be considered "done" for now.
