### ISSUE TITLE
Lean --server not working on "Untitled-1" unsaved files.

### ISSUE THREAD

**Issue by lovettchris** [leanprover/vscode-lean4#92]
Repro:
1. Launch VS code with no folder open
2. File/New File
3. Command Palette: Change Language Mode
4. select "Lean 4", wait for lean server to start
5. Now edit the new file and add `#eval 4+5`

No answer appears in the InfoView, in fact the infoview seems to always show nothing.  In debugging some things are different in the LSP protocol - for example "didOpen" never fires...

**Comment by gebner** [comment]
I believe that's because we only activate the language client for the `file://` URL schema:
```typescript
const documentSelector: DocumentFilter = {
    scheme: 'file',
    language: 'lean4',
}
```
