### ISSUE TITLE
Bootstrap could prompt user with known good releases

### ISSUE THREAD

**Issue by lovettchris** [leanprover/vscode-lean4#96]
In the case there is no elan installed and no lean-toolchain file found in the workspace, we could prompt the user with a list of known good toolchains by doing an http query against https://github.com/leanprover/lean4-nightly/releases then prompt for them to select one of those, then install that version.

**Comment by mhuisi** [comment]
We now always use `leanprover/lean4:stable` for bootstrapping and once leanprover/elan#106 is released, it will always resolve to the most recent stable toolchain. We would prefer this default as it ensures that users are on a recent stable version when creating new projects or using untitled files.
